#!/bin/sh
set -e

exec >/tmp/hx-uci-99-finish.log 2>&1

# Apply network/dhcp changes
/etc/init.d/network restart || true
/etc/init.d/dnsmasq restart || true

# # Apply wifi (if wifi exists)
wifi reload || wifi up || true

# # ✅ Ensure firewall is enabled and running
/etc/init.d/firewall enable || true
/etc/init.d/firewall restart || /etc/init.d/firewall start || true
# /etc/init.d/rpcd restart || true

/etc/init.d/uhttpd restart || true


echo "[OK] finish done"
exit 0
  
   
 
