#!/bin/sh
set -e

. /usr/lib/hxwrt/log.sh
hx_log_redirect "uci-defaults" "99-hx-finish.log"

# Apply network/dhcp changes
/etc/init.d/network restart || true
/etc/init.d/dnsmasq restart || true

# # Apply wifi (if wifi exists)
wifi reload || wifi up || true

# # ✅ Ensure firewall is enabled and running
/etc/init.d/firewall enable || true
/etc/init.d/firewall restart || /etc/init.d/firewall start || true
# /etc/init.d/rpcd restart || true

# Ensure uhttpd is enabled and running
/etc/init.d/uhttpd enable || true
/etc/init.d/uhttpd restart || /etc/init.d/uhttpd start || true


echo "[OK] finish done"
exit 0
  
   
 
