include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-hxwrt
PKG_RELEASE:=1

LUCI_TITLE:=HX-WRT Settings (minimal)
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
