#!/bin/sh
. /usr/lib/hxwrt/log.sh

iface="$INTERFACE"
action="$ACTION"
dev="$DEVICE"
proto="$PROTO"

hx_log_init "net" "net.log"

hx_log I "iface hotplug: action=${action} iface=${iface} dev=${dev} proto=${proto}"

# Optional: dump key ip info on ifup/ifdown
if [ "$action" = "ifup" ] || [ "$action" = "ifdown" ]; then
  ip -br a 2>/dev/null | sed 's/^/ip: /' | while read -r line; do
    hx_log D "$line"
  done
fi
