#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/env.sh"

log() { echo "[BRAND] $*"; }

# =========================
# Config (override via env)
# =========================
HXWRT_MODEL_SHORT="${HXWRT_MODEL_SHORT:-WR3000K}"

# Release branding (written into overlay)
HXWRT_DIST="${HXWRT_DIST:-HX-WRT}"
HXWRT_RELEASE="${HXWRT_RELEASE:-main}"          # user-facing version (hide SNAPSHOT)
HXWRT_TARGET="${HXWRT_TARGET:-mediatek/filogic}"
HXWRT_ARCH="${HXWRT_ARCH:-aarch64_cortex-a53}"

# Revision: auto from OpenWrt git if not provided
HXWRT_REVISION="${HXWRT_REVISION:-}"

# LuCI branding (user-facing)
HXWRT_LUCI_VARIANT="${HXWRT_LUCI_VARIANT:-LuCI Stable}"  # replace "LuCI Master"

# Paths
OPENWRT_DIR="${OPENWRT_DIR:?OPENWRT_DIR not set}"
HXWRT_DIR="${HXWRT_DIR:?HXWRT_DIR not set}"

# =========================
# 1) Patch DTS model string
# =========================
patch_dts_model() {
  local dts_root="${OPENWRT_DIR}/target/linux/mediatek/dts"
  [ -d "${dts_root}" ] || { log "skip dts patch: ${dts_root} not found"; return 0; }

  local hits
  hits="$(grep -RIl 'model = "Tenbay WR3000K"' "${dts_root}" 2>/dev/null || true)"

  if [ -z "${hits}" ]; then
    log "skip dts patch: no file contains model = \"Tenbay WR3000K\""
    return 0
  fi

  local f
  while IFS= read -r f; do
    log "patch dts model: ${f}"
    sed -i 's/model = "Tenbay WR3000K";/model = "'"${HXWRT_MODEL_SHORT}"'";/g' "${f}"
  done <<< "${hits}"

  log "dts patch done"
}

# =========================
# 2) Generate branded release files into hx-wrt overlay
#    NOTE: your procd only reads /usr/lib/os-release, so OPENWRT_* keys are required
# =========================
detect_openwrt_revision() {
  if [ -z "${HXWRT_REVISION}" ]; then
    if [ -d "${OPENWRT_DIR}/.git" ]; then
      local cnt sha
      cnt="$(git -C "${OPENWRT_DIR}" rev-list --count HEAD 2>/dev/null || true)"
      sha="$(git -C "${OPENWRT_DIR}" rev-parse --short HEAD 2>/dev/null || true)"
      if [ -n "${cnt}" ] && [ -n "${sha}" ]; then
        HXWRT_REVISION="r${cnt}-${sha}"
      fi
    fi
  fi
  HXWRT_REVISION="${HXWRT_REVISION:-unknown}"
}


write_overlay_release_files() {
  detect_openwrt_revision

  local overlay="${HXWRT_DIR}/overlay"
  mkdir -p "${overlay}/etc" "${overlay}/usr/lib"

  local desc="${HXWRT_DIST} ${HXWRT_RELEASE} ${HXWRT_REVISION}"

  log "write overlay /etc/openwrt_release"
  cat > "${overlay}/etc/openwrt_release" <<EOF
DISTRIB_ID='${HXWRT_DIST}'
DISTRIB_RELEASE='${HXWRT_RELEASE}'
DISTRIB_REVISION='${HXWRT_REVISION}'
DISTRIB_TARGET='${HXWRT_TARGET}'
DISTRIB_ARCH='${HXWRT_ARCH}'
DISTRIB_DESCRIPTION='${desc}'
EOF

  log "write overlay /etc/openwrt_version"
  echo "${HXWRT_REVISION}" > "${overlay}/etc/openwrt_version"

  # IMPORTANT: procd in your build reads /usr/lib/os-release (verified by strings /sbin/procd).
  # Provide OPENWRT_* keys so ubus 'system board' can expose target/revision/description properly.
  log "write overlay /usr/lib/os-release + /etc/os-release (with OPENWRT_* fields)"
  cat > "${overlay}/usr/lib/os-release" <<EOF
NAME="${HXWRT_DIST}"
VERSION="${HXWRT_RELEASE}"
ID="hx-wrt"
PRETTY_NAME="${HXWRT_DIST} ${HXWRT_RELEASE}"
VERSION_ID="${HXWRT_RELEASE}"

OPENWRT_RELEASE="${HXWRT_RELEASE}"
OPENWRT_REVISION="${HXWRT_REVISION}"
OPENWRT_BOARD="${HXWRT_TARGET}"
OPENWRT_ARCH="${HXWRT_ARCH}"
EOF

  # Avoid split-brain: make /etc/os-release identical
  cp -f "${overlay}/usr/lib/os-release" "${overlay}/etc/os-release"

  log "overlay release files done (${desc})"
}

# =========================
# 3) Patch LuCI "Master" exposure (real root cause: /usr/share/ucode/luci/version.uc)
#    The file is generated by: feeds/luci/modules/luci-base/src/Makefile
# =========================
patch_luci_master() {
  local luci_root="${OPENWRT_DIR}/feeds/luci"
  [ -d "${luci_root}" ] || { log "skip luci patch: ${luci_root} not found"; return 0; }

  log "patch luci root: ${luci_root}"

  # 3.1 luci.mk: UI variant string
  local luci_mk="${luci_root}/luci.mk"
  if [ -f "${luci_mk}" ]; then
    if grep -q 'variant="LuCI Master"' "${luci_mk}"; then
      log "patch luci.mk variant: LuCI Master -> ${HXWRT_LUCI_VARIANT}"
      sed -i 's/variant="LuCI Master"/variant="'"${HXWRT_LUCI_VARIANT}"'"/g' "${luci_mk}"
    else
      log "luci.mk variant already not 'LuCI Master' (skip)"
    fi
  fi

  # 3.2 luci-base src/Makefile: generates /usr/share/ucode/luci/version.uc
  local luci_base_src_mk="${luci_root}/modules/luci-base/src/Makefile"
  if [ -f "${luci_base_src_mk}" ]; then
    # Replace any generator assignment that uses LUCI_GITBRANCH
    if grep -q "LUCI_GITBRANCH" "${luci_base_src_mk}"; then
      log "patch luci-base generator: LUCI_GITBRANCH -> ${HXWRT_LUCI_VARIANT}"
      sed -i -E "s/^(.*branch[[:space:]]*=[[:space:]]*)['\"]?\\\$\\(LUCI_GITBRANCH\\)['\"]?(.*)$/\\1'${HXWRT_LUCI_VARIANT}'\\2/g" "${luci_base_src_mk}"
    fi

    # Extra safety: replace literal 'LuCI Master' if present
    if grep -q "LuCI Master" "${luci_base_src_mk}"; then
      log "patch luci-base literal: LuCI Master -> ${HXWRT_LUCI_VARIANT}"
      sed -i "s/LuCI Master/${HXWRT_LUCI_VARIANT}/g" "${luci_base_src_mk}"
    fi
  fi

  log "luci patch done"
}

hxwrt_write_build_id() {
  # Generate build identifier:
  #   YYYYMMDD-HHMM-gitshort
  # and write into HXWRT overlay (becomes /rom/etc/hxwrt_build_id)
  local overlay="${HXWRT_DIR}/overlay"
  local ts gitshort bid

  ts="$(date +%Y%m%d-%H%M 2>/dev/null || echo 00000000-0000)"

  # Prefer hx-wrt repo git, fallback to OPENWRT repo git, then nogit
  gitshort="$(git -C "${HXWRT_DIR}" rev-parse --short HEAD 2>/dev/null \
    || git -C "${OPENWRT_DIR}" rev-parse --short HEAD 2>/dev/null \
    || echo nogit)"

  bid="${ts}-${gitshort}"

  mkdir -p "${overlay}/etc" 2>/dev/null || true
  printf '%s\n' "${bid}" > "${overlay}/etc/hxwrt_build_id"

  mkdir -p "${overlay}/etc/hx-wrt" 2>/dev/null || true
  {
    echo "build_id=${bid}"
    echo "build_time=${ts}"
    echo "git_short=${gitshort}"
  } > "${overlay}/etc/hx-wrt/build-info"

  log "build_id written: ${bid}"
}



main() {
  log "start: model='${HXWRT_MODEL_SHORT}', dist='${HXWRT_DIST}', release='${HXWRT_RELEASE}', luci='${HXWRT_LUCI_VARIANT}'"

  patch_dts_model
  write_overlay_release_files
  patch_luci_master
  hxwrt_write_build_id

  log "all done"
}

main "$@"
