#!/bin/sh /etc/rc.common
START=20
STOP=10
USE_PROCD=1

NAME="hx-openclash-healthcheck"
PROG="/usr/bin/hx-openclash-healthcheck"

start_service() {
  [ -x "$PROG" ] || return 0

  procd_open_instance
  procd_set_param command /bin/sh -c "sleep 10; $PROG"
  procd_set_param respawn 0 0 0
  procd_close_instance
}

stop_service() {
  return 0
}
